add unit test for nominal case (encoding "hello\n")

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -7,14 +7,25 @@ AM_LDFLAGS=$(all_libraries)
 
 bin_PROGRAMS=a2cass
 
-a2cass_SOURCES=a2cass.c
+a2cass_SOURCES=a2cass.c a2cass_opt.c
 
+
+
+define_new_md5: all
+	echo "hello" | ./a2cass | $(MD5SUM) --binary >$(srcdir)/hello.md5
 
 check_SCRIPTS=unit_test.sh
 TESTS=$(check_SCRIPTS)
 
 unit_test.sh: .FORCE
-	echo "./a2cass --test" >>$@
+	touch $@
+	if test "X$(MD5SUM)" == X ; \
+	then \
+		echo "echo \"md5sum program not found, so cannot run this test\" >&2" >>$@ ; \
+		echo "exit 1" >>$@ ; \
+	else \
+		echo "echo \"hello\" | ./a2cass | $(MD5SUM) --check --status --warn $(srcdir)/hello.md5" >>$@ ; \
+	fi
 	chmod +x $@
 
 
